name: 'afrotix'
version: '1.0.0'
config-version: 2

profile: 'afrotix'

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  afrotix:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
